import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          "flex min-h-dvh flex-col overflow-hidden font-sans text-a16 antialiased bg-[#e9e9e9]"
        }
      >
        <Header />
        <main className="wrapper wrapper-padding flex flex-1 items-start justify-start py-0 md:pr-0">
          <div className="w-app-container flex-1 overflow-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
